title: Lakshmikanth
logo: /assets/img/logo.jfif
favi_icon: /assets/img/favicon.svg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
linkedin: lakshmikanth1999
github_url: lakshmikanth1999
mail_address: lakshmikanthk1999@gmail.com
phone_number: +919606517423
location: Bengaluru
job_position: Open for work
resume: /docs/Resume.pdf